
export const themes = [
    { name: "light", emoji: "🌞" },
    { name: "dark", emoji: "🌚" },
    { name: "cupcake", emoji: "🧁" },
    { name: "bumblebee", emoji: "🐝" },
    { name: "emerald", emoji: "💚" },
    { name: "corporate", emoji: "🏢" },
    { name: "synthwave", emoji: "🌅" },
    { name: "retro", emoji: "📼" },
    { name: "cyberpunk", emoji: "🤖" },
    { name: "valentine", emoji: "💖" },
    { name: "halloween", emoji: "🎃" },
    { name: "forest", emoji: "🌲" },
    { name: "aqua", emoji: "💧" },
    { name: "luxury", emoji: "💎" },
    { name: "dracula", emoji: "🧛" },
    { name: "cmyk", emoji: "🖨️" },
    { name: "autumn", emoji: "🍂" },
    { name: "business", emoji: "💼" },
    { name: "acid", emoji: "🧪" },
    { name: "lemonade", emoji: "🍋" },
    { name: "night", emoji: "🌃" },
    { name: "coffee", emoji: "☕" },
    { name: "winter", emoji: "❄️" },
];
